// sectionData.js

export const sectionInfo = {
    "Section 1": "Section 1 - Title and extent of operation of the Code.",
    "Section 2": "Section 2 - Punishment of offences committed within India.",
    "Section 3": "Section 3 - Punishment of offences committed beyond, but which by law may be tried within, India.",
    "Section 4": "Section 4 - Extension of Code to extra-territorial offences.",
    "Section 5": "Section 5 - Certain laws not to be affected by this Act.",
    "Section 6": "Section 6 - Definitions in the Code to be understood subject to exceptions.",
    "Section 7": "Section 7 - Sense of expression once explained.",
    "Section 8": "Section 8 - Gender.",
    "Section 9": "Section 9 - Number.",
    "Section 10": "Section 10 - 'Man'. 'Woman'.",
    "Section 11": "Section 11 - 'Person'.",
    "Section 12": "Section 12 - 'Public'.",
    "Section 13": "Section 13 - [Omitted].",
    "Section 14": "Section 14 - 'Servant of Government'.",
    "Section 15": "Section 15 - [Repealed].",
    "Section 16": "Section 16 - [Repealed].",
    "Section 17": "Section 17 - 'Government'.",
    "Section 18": "Section 18 - 'India'.",
    "Section 19": "Section 19 - 'Judge'.",
    "Section 20": "Section 20 - 'Court of Justice'.",
    "Section 21": "Section 21 - 'Public servant'.",
    "Section 22": "Section 22 - 'Moveable property'.",
    "Section 23": "Section 23 - 'Wrongful gain'.",
    "Section 24": "Section 24 - 'Wrongful loss'.",
    "Section 25": "Section 25 - 'Dishonestly'.",
    "Section 26": "Section 26 - 'Fraudulently'.",
    "Section 27": "Section 27 - 'Reason to believe'.",
    "Section 28": "Section 28 - 'Property'.",
    "Section 29": "Section 29 - 'Document'.",
    "Section 30": "Section 30 - 'Valuable security'.",
    "Section 31": "Section 31 - 'A will'.",
    "Section 32": "Section 32 - 'Words referring to acts include illegal omissions'.",
    "Section 33": "Section 33 - 'Act'.",
    "Section 34": "Section 34 - 'Common intention'.",
    "Section 35": "Section 35 - 'Act done by a person bound, or by mistake of fact believing himself bound, by law'.",
    "Section 36": "Section 36 - 'Act of Judge when acting judicially'.",
    "Section 37": "Section 37 - 'Act done pursuant to the judgment or order of Court'.",
    "Section 38": "Section 38 - 'Act done by a person justified, or by mistake of fact believing himself justified, by law'.",
    "Section 39": "Section 39 - 'Accident in doing a lawful act'.",
    "Section 40": "Section 40 - 'Punishment of offences committed within India'.",
    "Section 41": "Section 41 - 'Punishment of offences committed beyond, but which by law may be tried within, India'.",
    "Section 42": "Section 42 - 'Extension of Code to extra-territorial offences'.",
    "Section 43": "Section 43 - 'Certain laws not to be affected by this Act'.",
    "Section 44": "Section 44 - 'Definitions in the Code to be understood subject to exceptions'.",
    "Section 45": "Section 45 - 'Sense of expression once explained'.",
    "Section 46": "Section 46 - 'Gender'.",
    "Section 47": "Section 47 - 'Number'.",
    "Section 48": "Section 48 - 'Man'. 'Woman'.",
    "Section 49": "Section 49 - 'Person'.",
    "Section 50": "Section 50 - 'Public'.",
    "Section 51": "Section 51 - [Omitted].",
    "Section 52": "Section 52 - 'Servant of Government'.",
    "Section 53": "Section 53 - 'Government'.",
    "Section 54": "Section 54 - 'India'.",
    "Section 55": "Section 55 - 'Judge'.",
    "Section 56": "Section 56 - 'Court of Justice'.",
    "Section 57": "Section 57 - 'Public servant'.",
    "Section 58": "Section 58 - 'Moveable property'.",
    "Section 59": "Section 59 - 'Wrongful gain'.",
    "Section 60": "Section 60 - 'Wrongful loss'.",
    "Section 61": "Section 61 - 'Dishonestly'.",
    "Section 62": "Section 62 - 'Fraudulently'.",
    "Section 63": "Section 63 - 'Reason to believe'.",
    "Section 64": "Section 64 - 'Property'.",
    "Section 65": "Section 65 - 'Document'.",
    "Section 66": "Section 66 - 'Valuable security'.",
    "Section 67": "Section 67 - 'A will'.",
    "Section 68": "Section 68 - 'Words referring to acts include illegal omissions'.",
    "Section 69": "Section 69 - 'Act'.",
    "Section 70": "Section 70 - 'Common intention'.",
    "Section 71": "Section 71 - 'Act done by a person bound, or by mistake of fact believing himself bound, by law'.",
    "Section 72": "Section 72 - 'Act of Judge when acting judicially'.",
    "Section 73": "Section 73 - 'Act done pursuant to the judgment or order of Court'.",
    "Section 74": "Section 74 - 'Act done by a person justified, or by mistake of fact believing himself justified, by law'.",
    "Section 75": "Section 75 - 'Accident in doing a lawful act'.",
    // Add more sections as needed
  };
  